export interface ExtractedRequirement {
  id: number;
  transcript_id: number;
  client_id: number | null;
  client_name: string | null;
  budget_max: number | null;
  locations: string[];
  must_haves: string[];
  nice_to_haves: string[];
  property_type: string | null;
  property_types: string[];
  min_beds: number | null;
  min_baths: number | null;
  min_full_baths: number | null;
  min_total_baths: number | null;
  min_sqft: number | null;
  min_total_parking: number | null;
  min_garage_spaces: number | null;
  garage_type: string | null;
  basement_required: boolean | null;
  basement_finished: boolean | null;
  basement_separate_entrance: boolean | null;
  basement_legal_suite: boolean | null;
  city: string | null;
  sub_area: string | null;
  school_requirement: string | null;
  timeline: string | null;
  financing_type: string | null;
  confidence_score: number | null;
  llm_provider: string | null;
  llm_model: string | null;
  is_edited: boolean;
  created_at: string;
  updated_at: string;
}

export interface RequirementUpdate {
  client_name?: string;
  budget_max?: number;
  locations?: string[];
  must_haves?: string[];
  nice_to_haves?: string[];
  property_type?: string;
  property_types?: string[];
  min_beds?: number;
  min_baths?: number;
  min_full_baths?: number;
  min_total_baths?: number;
  min_sqft?: number;
  min_total_parking?: number;
  min_garage_spaces?: number;
  garage_type?: string;
  basement_required?: boolean;
  basement_finished?: boolean;
  basement_separate_entrance?: boolean;
  basement_legal_suite?: boolean;
  city?: string;
  sub_area?: string;
  school_requirement?: string;
  timeline?: string;
  financing_type?: string;
}
